 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        dashboard = new javax.swing.JButton();
        bill = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        stock = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        cusInfo = new javax.swing.JButton();
        recipt = new javax.swing.JButton();
        store = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(51, 51, 51));
        login.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 80, -1));

        dashboard.setBackground(new java.awt.Color(51, 51, 51));
        dashboard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("DashBoard");
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        jPanel1.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 150, -1));

        bill.setBackground(new java.awt.Color(51, 51, 51));
        bill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bill.setForeground(new java.awt.Color(255, 255, 255));
        bill.setText("Bill");
        bill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });
        jPanel1.add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        logout.setBackground(new java.awt.Color(51, 51, 51));
        logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        stock.setBackground(new java.awt.Color(51, 51, 51));
        stock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stock.setForeground(new java.awt.Color(255, 255, 255));
        stock.setText("Stock");
        stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        jPanel1.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 80, -1));

        exit.setBackground(new java.awt.Color(51, 51, 51));
        exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Logout");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 170, -1));

        cusInfo.setBackground(new java.awt.Color(51, 51, 51));
        cusInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cusInfo.setForeground(new java.awt.Color(255, 255, 255));
        cusInfo.setText("Customer Details");
        cusInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cusInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusInfoActionPerformed(evt);
            }
        });
        jPanel1.add(cusInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        recipt.setBackground(new java.awt.Color(51, 51, 51));
        recipt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        recipt.setForeground(new java.awt.Color(255, 255, 255));
        recipt.setText("Bill");
        recipt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reciptActionPerformed(evt);
            }
        });
        jPanel1.add(recipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 170, -1));

        store.setBackground(new java.awt.Color(51, 51, 51));
        store.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        store.setForeground(new java.awt.Color(255, 255, 255));
        store.setText("Stock");
        store.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        store.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeActionPerformed(evt);
            }
        });
        jPanel1.add(store, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 170, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 900, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        Stock p = new Stock();
        p.setVisible(true);
        
        //DashBoard l = new DashBoard();
        this.dispose();
    }//GEN-LAST:event_stockActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
         login q = new login();
        q.setVisible(true);
        
        //DashBoard l = new DashBoard();
        this.dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
         Bill r = new Bill();
        r.setVisible(true);
        
        //DashBoard l = new DashBoard();
        this.dispose();
    }//GEN-LAST:event_billActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
         this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void cusInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusInfoActionPerformed
        CustomerInfo_1 s = new CustomerInfo_1();
        s.setVisible(true);
        
        //DashBoard l = new DashBoard();
        this.dispose();
    }//GEN-LAST:event_cusInfoActionPerformed

    private void storeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeActionPerformed
       Stock x = new Stock();
        x.setVisible(true);
        
        //DashBoard l = new DashBoard();
        this.dispose();
    }//GEN-LAST:event_storeActionPerformed

    private void reciptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reciptActionPerformed
       Bill y = new Bill();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reciptActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
         this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
     DashBoard z = new DashBoard();
        z.setVisible(true);
        
        //DashBoard l = new DashBoard();
        this.dispose();
    }//GEN-LAST:event_dashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bill;
    private javax.swing.JButton cusInfo;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JButton logout;
    private javax.swing.JButton recipt;
    private javax.swing.JButton stock;
    private javax.swing.JButton store;
    // End of variables declaration//GEN-END:variables
}
