import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        juser = new javax.swing.JTextField();
        bloging = new javax.swing.JButton();
        jpassword = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        bexit1 = new javax.swing.JButton();
        jcshow_password = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGING");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 360, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("UserName");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, 28));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 190, 30));

        juser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juserActionPerformed(evt);
            }
        });
        jPanel2.add(juser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 360, 40));

        bloging.setBackground(new java.awt.Color(102, 255, 102));
        bloging.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bloging.setForeground(new java.awt.Color(255, 255, 255));
        bloging.setText("Loging ");
        bloging.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bloging.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bloging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogingActionPerformed(evt);
            }
        });
        jPanel2.add(bloging, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 130, 40));

        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 360, 40));

        register.setBackground(new java.awt.Color(153, 153, 255));
        register.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Register");
        register.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel2.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 140, 50));

        bexit1.setBackground(new java.awt.Color(255, 51, 51));
        bexit1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bexit1.setForeground(new java.awt.Color(255, 255, 255));
        bexit1.setText("Exit");
        bexit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bexit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexit1ActionPerformed(evt);
            }
        });
        jPanel2.add(bexit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 140, 50));

        jcshow_password.setText("Show Password");
        jcshow_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcshow_passwordActionPerformed(evt);
            }
        });
        jPanel2.add(jcshow_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 122, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void juserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juserActionPerformed

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

        // TODO add your handling code here:
        register r = new register();
        r.setVisible(true);
        
        //login l = new login();
        this.dispose();
        
    }//GEN-LAST:event_registerActionPerformed

    private void blogingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogingActionPerformed
        // TODO add your handling code here:
           try{ 
            String tun = juser.getText();
            String tpw = jpassword.getText();
            ResultSet rs = dbcon.SEARCH("SELECT * FROM admin");

            if(tun.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please Enter Username Here!!!","ERROR",JOptionPane.ERROR_MESSAGE);
                juser.grabFocus();
            }else{
                if(tpw.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Please Enter Password Here!!!","ERROR",JOptionPane.ERROR_MESSAGE);
                    jpassword.grabFocus();
                }else{
                    while (rs.next()) {
                        String un = rs.getString("username");                  
                        String pw = rs.getString("password");

                        if(un.equals(tun)){
                            if(pw.equals(tpw)){
                                
                                    DashBoard a = new DashBoard();
                                    a.setVisible(true);
                                    this.dispose();
                                                                    
                            }else{
                                JOptionPane.showMessageDialog(this,"Please Enter Correct Password", "ERROR",JOptionPane.ERROR_MESSAGE);
                                                             
                            }
                        }else{
                            //JOptionPane.showMessageDialog(this,"Please Enter Correct Username", "ERROR",JOptionPane.ERROR_MESSAGE);
                            //username_txt.setText(null);
                            //username_txt.grabFocus();
                        }
                    }
                }
            }

        } catch (Exception e) {
        }
       
    }//GEN-LAST:event_blogingActionPerformed

    private void jcshow_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcshow_passwordActionPerformed
        // TODO add your handling code here:
        if (jcshow_password.isSelected()){
            jpassword.setEchoChar((char)0);
        }
        else{
            jpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jcshow_passwordActionPerformed

    private void bexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexit1ActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_bexit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bexit1;
    private javax.swing.JButton bloging;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jcshow_password;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField juser;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
